### ISSUE TITLE
WMS Link Definition

### ISSUE THREAD

**Issue by cici004** [ishiland/cmv-wms-basemaps#1]
I was reading wmsBasemaps.js under config. I saw  id: 'Natural2015', id: 'Infrared2015',id: 'Natural2013'... where these WMS URLs were defined?

Thanks!

**Comment by ishiland** [comment]
Hi, 
An initial WMS service url is set in the `wmsConfig` property. From there, the visible layer within that service can be be toggled based on the selected layer.  Check out [ArcGIS Javascript API WMSLayer](https://developers.arcgis.com/javascript/3/jsapi/wmslayer-amd.html#).

**Comment by ishiland** [comment]
New release with config changes
